### ISSUE TITLE
Custom map wallpaper

### ISSUE THREAD

**Issue by WebSnke** [D0-0K/themify#11]
Hey, I really like this project and that's why I would like to know how you made the map wallpaper.
I would like to create my own of other cities and add them to the Patreon ones.

Thanks in advance
WebSnke

**Comment by D0-0K** [comment]
Hey there! It's been a long time since I made those wallpapers so I don't remember exactly, but I think I could've used OpenStreetMap? From what I do remember, it allows you to download maps as SVGs, which I would then make gray and transparent before exporting as bitmaps.
Themify 2 will treat wallpapers a lot differently and will most likely require an automated process using scripts to create wallpaper packs. I will absolutely keep you in mind when making these and hopefully make it as easy as possible to make your own city maps!
-Dook

**Comment by WebSnke** [comment]
> Hey there! It's been a long time since I made those wallpapers so I don't remember exactly, but I think I could've used OpenStreetMap? From what I do remember, it allows you to download maps as SVGs, which I would then make gray and transparent before exporting as bitmaps. Themify 2 will treat wallpapers a lot differently and will most likely require an automated process using scripts to create wallpaper packs. I will absolutely keep you in mind when making these and hopefully make it as easy as possible to make your own city maps! -Dook

Thanks. I am really looking forward to Themify 2.
